spring:
  profiles:
    include: secret
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/members/**, /signUp, /signIn

        - id: question-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/questions/**, /questions/**

        - id: vote-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/votes/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**, /connect

