spring:
  profiles:
    include: secret
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/member/**, /signUp, /signIn

#        - id: order-service
#          uri: http://order-service:8082
#          predicates:
#            - Path=/api/order/**

